services:
    h1api:
        image: elfensky/h1api:latest # Replace with the correct image name and tag
        container_name: h1api # Optional: name your container
        env_file:
            - .env
        volumes:
            - /path/on/host:/app/data
        restart: unless-stopped # Automatically restart the container unless it is explicitly stopped
