services:
    h1api:
        image: elfensky/h1api:latest
        container_name: h1api # Optional: name your container
        ports:
            - '52001:3000'
        environment:
            - DATABASE_URL=${DATABASE_URL}
            - SENTRY_DSN=${SENTRY_DSN}
        restart: unless-stopped
        network_mode: bridge # Use the default, ufw-whitelisted Docker Network
        extra_hosts:
            - 'host.docker.internal:host-gateway' # pass the host to container, required on linux
