name: Automate Release
# on:
#     push:
#         tags:
#             - '*.*.*' # Triggers on version tags like v1.0.0
on:
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.ACCESS_TOKEN }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: |
                      ghcr.io/${{ github.repository_owner }}/h1api:${{ github.ref_name }}
                      ghcr.io/${{ github.repository_owner }}/h1api:latest

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v2
              with:
                  files: CHANGELOG.md
                  body_path: CHANGELOG.md
                  token: ${{ secrets.GITHUB_TOKEN }}

            #   with:
            #       tag_name: ${{ github.ref_name }}
            #       name: Release ${{ github.ref_name }}
            #       body: |
            #           Docker image available at:
            #           - `ghcr.io/${{ github.repository_owner }}/h1api:${{ github.ref_name }}`
            #           - `ghcr.io/${{ github.repository_owner }}/h1api:latest`
            #   env:
            #       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
